spring.application.name=portfolio-backend
spring.data.mongodb.uri=mongodb+srv://bitraguntayeswanth2005_db_user:Yeswanth2005%4011@cluster0.vsa2a1j.mongodb.net/portfolio?retryWrites=true&w=majority
spring.data.mongodb.database=portfolio
server.port=${PORT:8081}
