spring.application.name=portfolio-backend
spring.data.mongodb.uri=mongodb+srv://bitraguntayeswanth2005_db_user:<db_password>@cluster0.vsa2a1j.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=portfolio
server.port=${PORT:8080}
